name: Base

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.0]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.node }}
          bundler-cache: true
      - name: Setup
        run: |
          bundle install --jobs 4 --retry 3
      - name: Lint
        run: bundle exec standardrb
      - name: Test
        run: bundle exec rspec
